$schema:     http://json-schema.org/draft-07/schema
$id:         https://schemas.digitallinguistics.io/Project.json
name:        Project
type:        object
description: An object containing information about a Digitalis project.
required:
  - permissions
  - type
properties:

  analysisLanguages:
    title:       Analysis Languages
    type:        array
    description: A list of analysis languages used by this project.
    items:
      $ref: https://schemas.digitallinguistics.io/LanguageTag.json

  dateCreated:
    title:       Date Created
    description: The date this project was created.

  dateModified:
    title:       Date Modified
    description: The date this project was last modified.

  defaultAnalysisLanguage:
    title:       Default Analysis Language
    $ref:        https://schemas.digitallinguistics.io/LanguageTag.json
    description: The default analysis language to use when displaying data for this project.

  id:
    title:       ID
    type:        string
    format:      uuid
    description: The ID for this database item.

  name:
    title:       Name
    $ref:        https://schemas.digitallinguistics.io/MultiLangString.json
    description: The name of the project.

  permissions:
    title:       Permissions
    $ref:        https://schemas.digitallinguistics.io/Permissions.json
    description: A permissions object.

  statuses:
    title:       Statuses
    $ref:        https://schemas.digitallinguistics.io/Statuses.json
    description: A set of checklists/workflows used in this project.

  type:
    title:       Type
    type:        string
    const:       Project
    readOnly:    true
    description: The type of object. Must be set to `Project`.