$schema:     http://json-schema.org/draft-07/schema
$id:         https://schemas.digitallinguistics.io/Project.json
name:        Project
type:        object
description: An object containing information about a Digitalis project.
required:
  - permissions
  - type
properties:

  id:
    title:       ID
    type:        string
    format:      uuid
    description: The ID for this database item.

  name:
    title:       Name
    $ref:        https://schemas.digitallinguistics.io/MultiLangString.json
    description: The name of the project.

  permissions:
    title:       Permissions
    $ref:        https://schemas.digitallinguistics.io/Permissions.json
    description: A permissions object.

  type:
    title:       Type
    type:        string
    const:       Project
    readOnly:    true
    description: The type of object. Must be set to `Project`.